sf:
  user: "ntnmule@prowesssoft.com.muledev"
  authURL : "https://ntnconnect--muledev.sandbox.my.salesforce.com/services/Soap/u/58.0"
  
db:
  host: "129.147.16.38"
  port: "1521"
  user: "c_mulesoft"
  service: "jdeorcl.netuenazr.vcnzgqox.oraclevcn.com"
  countQuery: "SELECT COUNT(*) FROM PRDDTA.F57JPNPM WHERE RCAA19 NOT LIKE '#%' 
  AND RCAA19 NOT LIKE '%#%'  AND RCI75MCHFD = 'Y'"
  query: "SELECT  RCAA19 ,RC74USTA FROM PRDDTA.F57JPNPM WHERE RCAA19 NOT LIKE '#%' 
  AND RCAA19 NOT LIKE '%#%' AND RCI75MCHFD = 'Y'"

pricebooks:
  host: "ntn-pricebooks-jde-sf-sync-app-prod-xbmlkc.xryhvh.usa-e2.cloudhub.io"
  port: "443"
  basePath : "/api/"
  uri : "pricebooks" 

smtp:
  host: "smtp.office365.com"
  port: "25"  
  to: "donotreply@ntnusa.com,ntnmule@prowesssoft.com"  