#DB config details
db:
  password: "![8M3rPy3SGjM=]"
  user: "![c6/KkkNKJ/o=]"
  


sf:
  token: "![pxS/bMSXsKXRM/Ph2PWwFqE1Lk9fXlTzNNGx3zwfAz8=]"
  password: "![2YNZt1lm+MRm7qkhAuEumw==]"
  key: "![EcXBTeWMMaVCEEi9WUaGSqE09nvQOCXB8A0KkGVWkyZOBaY1+m0B7te3JSWrKUPCfd9wxS9PIB5P3AFn9zrs5pg815nBHF0V3G8dltx78IhdjTzU31pnEA==]"
  secret: "![/R6rU6BCBm6HSsMJWPKTSd97S0VwGuQdqnnCRpYHdgJfJ7hb/Va5860uD6lVzmQ/95UtFnynjLulyE8DlNQGAyDIjV/aQhK2]"
    
smtp:
  user: "![hRt1ri9KnH7VngaJcayGZ0D8arLBERHy1f3i+Ca4XPI=]"
  password: "![BapbFMsL0srqwUVI3ICHLlxe4IERbHKP]"   