sf:
  user: "mulesoftintegration@ntnusa.com"
  authURL : "https://login.salesforce.com/services/Soap/u/56.0"
  URL: "https://ntnconnect.my.salesforce.com/services/oauth2/token"  
  
 #app name
app:
  name: "ntn-jpn-master-jde-sf-sync-app"  
  env: "PROD"     
  
db:
  host: "129.147.16.38"
  port: "1521"
  user: "c_mulesoft"
  service: "jdeorcl.netuenazr.vcnzgqox.oraclevcn.com"
  countQuery: "SELECT COUNT(*) FROM PRODDTA.F57JPNPM WHERE RCAA19 NOT LIKE '#%' 
  AND RCAA19 LIKE '%#%'  AND RCI75MCHFD = 'Y'"
  query: "SELECT  RCAA19 ,RC74USTA FROM PRODDTA.F57JPNPM WHERE RCAA19 NOT LIKE '#%' 
  AND RCAA19 LIKE '%#%' AND RCI75MCHFD = 'Y'"

pricebooks:
  host: "ntn-pricebooks-jde-sf-sync-app-prod-xbmlkc.xryhvh.usa-e2.cloudhub.io"
  port: "443"
  basePath : "/api/"
  uri : "pricebooks" 

smtp:
  host: "smtp.office365.com"
  port: "25"  
  to: "donotreply@ntnusa.com,ntnmule@prowesssoft.com"  